### ISSUE TITLE
Website is broken

### ISSUE THREAD

**Issue by Pandademic** [pmbanugo/shopping-list#3]
shopping-list.now.sh redirects to https://shopping-list.vercel.app/ which says :
404: NOT_FOUND
Code: NOT_FOUND
ID: iad1::4rpfm-1640991302883-89a3bcf9fc8e

**Comment by pmbanugo** [comment]
Thanks for informing me. I'm not actively maintaining this so I won't fix it anytime soon.

**Comment by Pandademic** [comment]
No Problem
